services:
  minecraft:
    image: itzg/minecraft-server:java21
    container_name: vexksaa
    restart: unless-stopped
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      VERSION: "1.21.8"
      MEMORY: "2G"
      MOTD: "Vexksaa"
      ENABLE_RCON: "false"
      ONLINE_MODE: "false"
    volumes:
      - ./test-server:/data
      - ./build/libs:/plugins:ro
